### ISSUE TITLE
Restructure code for version 2.0

### ISSUE THREAD

**Issue by solymosi** [solymosi/npu#12]
Ideas for improving code quality:

* Convert tabs to spaces, remove trailing whitespace.
* Use ES5 features instead of the corresponding jQuery helper functions (e.g. `$.inArray`).
* Don't use `$` for data storage by setting random properties on it (e.g. `$.examSubjectFilterCache` or `$.examListSubject`).
* Break source code out into multiple source files and use a preprocessor to generate the final script. Possibly minify it too, though that may decrease the trust in potential users that they aren't installing something malicious.
* Implement a small framework for splitting up functionality into separate, independent modules. Prevent modules from interfering with each other. Create a globally accessible place for generic helper methods. Have the page detection logic as part of the module framework. This will later allow us to let users selectively enable and disable specific features of the script.
* Refactor user data management functions `getUserData` and `setUserData` to make the parameterization more trivial.
* A common theme throughout the script is the use of a timer and a `data-*` marker to detect when Neptun reloads an element and reapply our enhancements if that happens. This could be extracted into a global function, which would set up the proper timers and markers and simply execute a callback function when it's time to perform the enhancements (again). Doing this would also let all enhancements share the same `setInterval` timer, improving performance. Example:

```javascript
npu.enhanceElement("#h_markbook_gridIndexEntry_bodytable", function() {
  // this is called whenever the element is recreated by Neptun
}
```

* Add a global function for easier injection of CSS styles. Example:

```javascript
npu.injectCssRule(".termSelect li", {
  "display": "inline-block",
  "vertical-align": "middle"
});
```

**Comment by polaroi8d** [comment]
There is something which is done from this list?

**Comment by solymosi** [comment]
I have a very rudimentary version of the framework written already, but it isn't nearly production ready yet. I'll publish it as soon as it's in working condition.

**Comment by polaroi8d** [comment]
Okey, if I can help you, pm me

**Comment by solymosi** [comment]
I'm working on this here: https://github.com/solymosi/npu/pull/56

**Comment by solymosi** [comment]
This is good enough for now.
