### ISSUE TITLE
Exams errorneously reported as completed

### ISSUE THREAD

**Issue by solymosi** [solymosi/npu#21]
User report:

> Vizsgajelentkezés lapon zöld színnel (azaz teljesítettként) jelöli azokat a tárgyakat, amik korábban már fel voltak véve, azonban nem lettek teljesítve. Mivel automatikusan a Teljesített tárgyak elrejtése volt beállítva, majdnem lemaradtam a vizsgákról.

I'll try to repro in the meantime.

@whisperity Do you have an idea what's causing this?

**Comment by whisperity** [comment]
What grades are written in the sub-table under the subject? Perhaps on other universities than mine a passing seminar grade is errorneously considered as a passing grade?

Or otherwise the function which handles the markupping of the exam list window falls into a trap if there isn't a subtable for the exam row?

Not sure, perhaps Neptun itself was changed. I haven't any subject which I failed in a previous semester so I can't check :(

**Comment by solymosi** [comment]
This is perhaps the only situation where not having failed any exams is a disadvantage 😂 

Maybe the label of the OP's grade is not in this list?
https://github.com/solymosi/npu/blob/master/npu.user.js#L1020-L1022
We only do a `trim` as input sanitization, so this fails if the labels are lowercase for example.

After reviewing the code I'm pretty sure that a missing subtable is not an issue.

I'll follow up with the OP to see if we can find out more.

**Comment by solymosi** [comment]
I've reached out to the OP.

Regardless of their response, we should probably whitelist _both_ the passing grades and the failing grades and only mark those that are present in one of the lists; otherwise we'd leave them in an "unknown" status and not hide the row. This would be a safer default.

**Comment by whisperity** [comment]
There is another issue, seemingly. I have exams subscribed to from all the subjects that has exams in the system. Yet, the dropdown on the exam list only colours one subject with yellow.

Something somewhere is missing from the internal representation.

**Comment by solymosi** [comment]
Got a screenshot from the OP. Looks like `Nem vizsgázott` is the problem, it's not on the list.

![image](https://user-images.githubusercontent.com/199790/33631482-998ed4d8-da02-11e7-8c37-91c9597ea407.png)

I'm going to prepare a PR with the double-whitelist functionality to prevent this problem in the future.

**Comment by whisperity** [comment]
Yeah, seems to be that we explicitly checked for values which are not Fail. Unfortunately while Neptun is deployed as some sort of a global version across all unis, there are these individual kinks.

"Did not attend" is not a valid *grade* at my uni. And I can confirm this from the Teacher site...
(Hah, I sometimes miss npu from the teacher facade...) For not taking the exam we have the "did not attend" checkbox, but that does not result in a grade being given.

#Standards and #BolognaSystem, right?

**Comment by solymosi** [comment]
Oh, you have teacher access? That's useful!

Guess what? Corvinus has "did not attend" as a valid (failing) grade that can be given for an exam, so you can have the status "attended" with the grade "did not attend" at the same time:

![capture](https://user-images.githubusercontent.com/199790/33633916-574745b2-da0a-11e7-8fc4-bf2c6c1bd07b.PNG)

![5aoxo](https://user-images.githubusercontent.com/199790/33633992-98f3eee8-da0a-11e7-820a-bba2e5452ac7.jpg)

I'm pretty sure unis can customize the grade names however they see fit, and in this particular case they simply have misconfigured them.

Also, there is a difference between giving a grade for a specific exam vs. grading the course directly. When I was studying at Corvinus, teachers would sometimes enter the grade directly for the course, leaving the exam without a grade. To this day I have those exams displayed in yellow, without a check mark.
