### ISSUE TITLE
Options + sign is hidden on "my exams" page

### ISSUE THREAD

**Issue by whisperity** [solymosi/npu#25]
@solymosi Could you please apply the fix you did on the exam registration page to the "My exams" page too? (Route code `0402`.) If an exam is registered but not yet graded (i.e. it has the yellow background), the `[+]` sign is hidden.

![image](https://user-images.githubusercontent.com/1969470/34359812-710258aa-ea5b-11e7-88ef-471b1495219d.png)

**Comment by solymosi** [comment]
@whisperity Can you please test this new version? https://github.com/solymosi/npu/raw/60d136219b8cc0ceafadd1cd83c1ba21070579d7/npu.user.js
PR: #27

**Comment by whisperity** [comment]
We have a Neptun shutdown for the weekend. After that, I'll be sure to test. Meanwhile, let me add another issue I have found!

**Comment by solymosi** [comment]
Cool, thanks - we might as well add that fix to this PR too.

**Comment by solymosi** [comment]
Released in 1.52.3 - thanks for reporting! 🎉 👍
