### ISSUE TITLE
Neptun's official "Ignore" button on unread messages produces two NPU-"Don't care" buttons

### ISSUE THREAD

**Issue by whisperity** [solymosi/npu#31]

**Comment by solymosi** [comment]
I am unable to reproduce on the ELTE Neptun :cry: 
Build: 455 (2018.07.19.) P20181009

![image](https://user-images.githubusercontent.com/199790/46702102-68d37900-cc11-11e8-9bd0-cd8703cf4213.png)

**Comment by whisperity** [comment]
Weird. Last time it didn't pop up for me either. Let's wait until next time I get something official, and if I can't give some more details on why this happens, I'll withdraw this issue.

**Comment by whisperity** [comment]
Yeah, seems to have gone away. It had a `Kihagy` text, btw, two buttons next to the already existing two. Maybe Neptun tried putting something in.
