### ISSUE TITLE
OMHV reports endless loading loop

### ISSUE THREAD

**Issue by NorbiPeti** [solymosi/npu#32]
On the OMHV reports page, the script constantly tries to load the list but there's nothing to choose from the dropdown (just the default text). The page reloads, then the script attempts to load it again, and so forth.

Build: 455 (2018.07.19.) P20181010

**Comment by solymosi** [comment]
I was unable to reproduce because I only have access to a Neptun where there _are_ entries on the OMHV reports page. Regardless, I will double-check what the code does when there are no terms to choose from on a page.
