### ISSUE TITLE
Neptun órarendtervező

### ISSUE THREAD

**Issue by balmazlitkey** [solymosi/npu#34]
Vizsgafelvétel kezdete előtt nincs lehetőség a vizsgaidőpontokat órarendtervezőbe adni. PPKE neptun.

**Comment by solymosi** [comment]
Az órarendtervező a Neptun beépített funkciója, nem a Neptun PowerUp!-hoz tartozik. Keresd a "Tárolás" gombot, az tartozik a NPU-hoz.
