### ISSUE TITLE
Vizsgatárolás funkció nem működik

### ISSUE THREAD

**Issue by Aron958** [solymosi/npu#35]
Tampermonkey hibaüzenet: Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!

Minden webhelyhez engedélyezve van az elérése, ennek ellenére nem tűnik el a hibaüzenet. Az összes funkció közül csak a beérkezett üzenetek elolvasását lehet mellőzni, a többi funkció nem működik.

ELTE Neptun

**Comment by solymosi** [comment]
> a többi funkció nem működik

Teszteltem a szkriptet a legújabb Chrome + TamperMonkey kombinációval, és minden működött az ELTE Neptun-on. Mi a pontos hibajelenség?

**Comment by Aron958** [comment]
A vizsgaadatokat megnyitva nincs lehetőség a vizsga tárolására. 

![vizsgák](https://user-images.githubusercontent.com/36742625/57178960-a67f4400-6e78-11e9-98c8-aaef00f0f6a4.PNG)

Chrome 74.0.3729.131 64bit

Próbáltam a 75.0.3770.18 _Beta 64bit alatt, ott sem ment, firefoxban szintén nem. Előfordulhat, hogy nálam van a hiba, vagy még nincsenek rendesen feltöltve a vizsgák?

**Comment by solymosi** [comment]
Megvan a probléma forrása: ilyen funkció soha nem is létezett :smile: 

> Az alábbi változtatások a vizsgajelentkezést hivatottak könnyíteni:
>
>    * A vizsgák automatikusan listázódnak, miután kiválasztottad a megfelelő félévet. A tárgyak listájában ráadásul csak azok a tárgyak jelennek meg, melyekhez tartozik legalább egy vizsga.
>    * A szkript módosít néhány színt az oldalon, hogy jobban lásd az egyes vizsgák állapotát. A vizsgaeredménnyel még nem rendelkező tárgyak felvett vizsgái sárga hátteret, a sikeresen teljesített tárgyak vizsgái zöld hátteret, a kizárólag sikertelen vizsgákkal rendelkező tárgyak vizsgái pedig piros hátteret kapnak.
>    * A vizsgajelentkezés oldalon lehetőség van elrejteni a már teljesített tárgyakhoz tartozó vizsgákat.

**Comment by Aron958** [comment]
Pedig rémlik valami ahhoz hasonló funkció mint a tárgyfelvételnél a tárgyak tárolása, csak vizsgákkal, mintha előző félévben használtam volna. Ha nincs így akkor köszi a segítséget és zárhatod az issue-t 😄
