### ISSUE TITLE
Drop out

### ISSUE THREAD

**Issue by Ceratuth** [solymosi/npu#36]
A neptun amint beléptem az órarendtervezőbe kidobott a bejelentkezési képernyőre, semmilyen hiba üzenetet nem kaptam.

**Comment by solymosi** [comment]
Ha az F12-t megnyomod, átváltasz a "Console" tab-ra és bekapcsolod a "Persist logs"-t, majd újra megpróbálod megnyitni az órarendet, látsz valamilyen hibaüzenetet?
