### ISSUE TITLE
not working intallation

### ISSUE THREAD

**Issue by Anesz** [solymosi/npu#37]
Szia! 
Nekem olyan gondom lenne hogy Chromeban és firefoxban is miután felraktam a tampermonkey-t és azon belül telepítem a scriptet azt elfogadja, de utána hiába megyek neptunra ott azt írja nem fut egyetlen script sem.
Mit csinálok rosszul?

**Comment by DorinaFerencsik** [comment]
Szia @Anesz!
Én is most telepítettem új gépre, hasonló problémával. Nálam az volt a gond hogy a chrome letiltotta a script futását. Ezt az URL sávban, a könyvjelzőkhöz adás csillag mellett megjelenő, piros x-el ellátott puzzle ikon jelzi.
Megoldás:
Kattints a puzzle ikonra és válaszd a "Nem biztonságos scriptek betöltése" linket, ezután ha nem tölt újra magától az oldal akkor érdemes frissíteni
