### ISSUE TITLE
Mark multiple mails as read

### ISSUE THREAD

**Issue by DanShepherd27** [solymosi/npu#42]
Please make an option to mark selected mails as read. It is very annoying that I have to open each mail separately, even if I've already read them in my emails. It's very hard to organize Neptun messages, I already have 44 unread, and when a teacher submits 30 exam dates by accident, I get 30 mail notifications (happened before). So this would be a very useful feature. Thanks!

**Comment by FeaXR** [comment]
Hey, I had the same issue, so I made a script which does something similar, if it helps use it
https://github.com/solymosi/npu/issues/43

**Comment by DanShepherd27** [comment]
Cool, thank you!

**Comment by solymosi** [comment]
Closing in favor of #43
