### ISSUE TITLE
The Neptun URL at the Corvinus has changed

### ISSUE THREAD

**Issue by danihorvath** [solymosi/npu#46]
Adding the line 
`// @include        https://*neptun*/*Hallgatoi*/*`
would fix it.

**Comment by solymosi** [comment]
It seems to be working for me with the current URL patterns, at least in Firefox. Which browser are you using?

**Comment by danihorvath** [comment]
Google Chrome for Mac, with Violentmonkey. The issue is probably with the case sensitivity.

**Comment by solymosi** [comment]
Ah, that must be it then. Feel free to prepare a MR and I'll merge & release it ASAP 🙂
