### ISSUE TITLE
Disable "Studies" automatically jumping to index for Vimium

### ISSUE THREAD

**Issue by whisperity** [solymosi/npu#52]
With [Vimium](http://addons.mozilla.org/en-US/firefox/addon/vimium-ff/), navigation is easier because pressing `f` will generate jump keys which you can use to "click" on elements. For example, "clicking" the menu for "Personal data" brings the dropdown, after which `f` and another sequence can take you to the page.

Typing in `f ea` here:
![image](https://user-images.githubusercontent.com/1969470/101215038-5fbd8580-367d-11eb-8596-2e942ba31c7d.png)
will bring the menu down properly, after which another `f` renders the new set of keys:
![image](https://user-images.githubusercontent.com/1969470/101215060-677d2a00-367d-11eb-9159-7fb7e93ac9db.png)

Whereas doing `f ga` or `f cc` will immediately jump, because "Studies" is clicked.

However, this is broken by the fact that simply "clicking" on "Studies" will jump to the index, without pulling the dropdown, as the dropdown is only there on the hover action now.
This makes the jump to target feature of Vimium useless...

I'm not sure if one could reasonably detect from within NPU that a browser addon is installed/running, so a checkbox that disables these "shortcuts" (preferably off by default, because it's highly unlikely that non-IT people will use something like Vimium...).
Same applies for the "subjects" going to registration and "exams" going to registration, too.

**Comment by solymosi** [comment]
Now that the code has been refactored in #56 it's easier to add a feature toggle for this. I'll look into it soon.

**Comment by solymosi** [comment]
A Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

Mivel ez az issue egy új funkcióról szól, az már egészen biztosan nem lesz lefejlesztve.
