### ISSUE TITLE
[HELP]Felturbózott szabad helyre várakozás használata?

### ISSUE THREAD

**Issue by hunorbatori** [solymosi/npu#61]
Hi!

Most szeretném elkezdeni használni a scriptet de nem egészen értem a readme alapján, hogy a [Felturbózott szabad helyre várakozást](https://github.com/solymosi/npu#felturb%C3%B3zott-szabad-helyre-v%C3%A1rakoz%C3%A1s)-t pontosan, hogy is kellene használnom.

Van egy tárgy, annak három meghirdetett gyakorlata, mind a három fullos. Bejelöltem őket és eltároltam. Hogyan lesz ebből minél gyorsabb tárgyfelvétel ahogy ürül egy hely?

Előre is köszi a segítséget!

**Comment by whisperity** [comment]
Sehogy. A "szabad hely" itt a belépéskori szabad helyet jelenti. Amikor nincs elég hely a Neptunba belépni (tárgyfelvételkor, vizsgafelvételkor, stb.) akkor X időnként a Neptun újra próbálkozna, na ezen segít egy picit, hogy ez gyorsabb legyen.

Ha már bejutottál a Neptunba, a tárgyat neked kell felvenned. Viszont a tárolt tárgyakra tudsz szűrni, és azon belül ha a tárgy adatlapját megnyitottad, a tárolt kurzusokat egy kattintással felvenni.

**Comment by hunorbatori** [comment]
Á, értem. Félre értelmeztem akkor a szabad hely fogalmát.

Köszönöm az infókat.
