### ISSUE TITLE
Nem működik az automatikus kiléptetés megakadályozása

### ISSUE THREAD

**Issue by HanTyumi98** [solymosi/npu#76]
Sajnos valamilyen okból kifolyólag az utóbbi időben (nem tudom pontosan, de augusztusban már biztos tapasztaltam) nem működik megfelelően az automatikus kiléptetést gátló mechanizmus és ugyanúgy kidob, ha x ideig tétlen maradsz. Károlis Neptunról van szó az esetemben, tavaszi tárgyfelvételnél még nem volt ilyen probléma.

**Comment by 0xGREG** [comment]
Én is ezt tapasztalom BCE-n.

**Comment by solymosi** [comment]
Teszteltem a kódot a BCE Neptun-on, és úgy tűnik, hogy a funkció továbbra is működik. Lehet, hogy az alábbiról van szó?

> Figyelem! Mivel a szkript a böngészőben fut, bizonyos típusú kidobásokat nem tud megakadályozni (pl. erős túlterheltség, IP cím változás vagy a szerver újraindítása esetén). Ezzel kapcsolatban nem kérek hibajelentéseket.
