### ISSUE TITLE
Nem elérhető a félév választó menü

### ISSUE THREAD

**Issue by bzslrts** [solymosi/npu#77]

**Comment by bzslrts** [comment]
Idén kezdtem az egyetemet és az npu használatát is. Közeledve a második félévhez szerettem volna megnézni a leendő tárgyaimat, viszont nincs lehetőségem félévet váltani az npu segítségével. Másik böngészőből elindítva az alap neptunos felületen ez a lehetőség adott továbbra is.

**Comment by whisperity** [comment]
@bzslrts A bal felső sarokban a képzés választó menü mellett mit ír? Ott kéne legyen egy írás hogy melyik képzésed van ki választva, benne a jogviszony kezdetének időpontja. Az alapján szűr a customizált félév nyomógombos része az NPU-nak, valószínűleg valami rosszul olvasódik fel.

Esetleg még Neptun kezdolaprol (mielőtt belépsz) a verziószámot is el tudod mondani? Nem az NPU-ét, hanem a Neptunét.

**Comment by bzslrts** [comment]
Ha rányomok a képzés választóra, akkor a megjelenő menüben nincs lehetőségem választani, mivel csak a jelenlegi képzés, jelenlegi féléve jelenik meg. Itt, a képzés választóban kellene lehetőségem legyen félévet választani, avgy az teljesen másik gomb kellene legyen? Mert dedikált félév választó nem is jelenik meg, bár mondom, nem tudom., hogy egyáltalán ez meg kellene-e, vagy a képzés választóban kéne legyen benne a következp félév.

A Neptun verziója pedig ez:
Verzió: 2022.3.10 (2022. 12. 02.)
PTE_HW3(577)

**Comment by whisperity** [comment]
Nem, ha csak egy képzésed van, akkor teljesen normális, hogy csak azt az egy képzést látod. Akkor lenne több képzésed, ha folytatnád MSc-n, doktorin, vagy akár párhuzamosan járnál egy másik szakra ugyanazon az egyetemen.

A dolognak a képzés választót megnyitó gomb / link **mellett** kellene lennie:

![Screenshot_20221207_153522](https://user-images.githubusercontent.com/1969470/206207033-38f2f461-c785-4123-9246-e91cc10b64be.png)

Itt lenyeli a túl hosszú szöveget, de ha megnézzük a HTML szerkezetét az oldalnak (jobb klikk a szövegre és lesz egy `Inspect` opció), akkor látható hogy a megjelenő `...` csak egy vizuális trükk, a teljes dokumentum "forráskódjában" ott van a dátum:
![Screenshot_20221207_153537](https://user-images.githubusercontent.com/1969470/206207206-a5c0caa2-41ae-4542-b1ba-0ea2fcdf5c49.png)

Az NPU ezt olvassa ki és állapítja meg melyik félév az első féléved, hogy elrejtse azon félévekhez tartozó gombokat (igen, néhány Neptun modul annyira nyomi, hogy odarakja neked 1990-ig visszamenőleg az összes félévet...) amik neked az adott képzésen nem relevánsak.

Szinte biztos vagyok benne, hogy ez az információ vagy hiányzik, vagy valami olyan formátumban van amit mi nem kezelünk jól, és ezért a rendszer azt hiszi, hogy egyetlen olyan félév sincs, amely releváns lenne, ezért az összes választógombot törli.

**Comment by bzslrts** [comment]
Jó és akkor mi tévő legyek végső soron, hogy tudjak váltani a félévek között?

**Comment by whisperity** [comment]
Te egyelőre még nem tudsz tenni közvetlenül semmit. Kérlek mutasd meg nekünk azt, hogy a ti Neptunotok mit és hogyan ír ki. Ha látjuk mit kéne kiolvasnunk, akkor meg tudjuk javítani a kódot, hogy értelmezze azt a formátumot (is). Sokkal újabb Neptunt futtattok, mint a BME (akiknél november 1-jei Neptun fut) és az ELTE (ahol ez az információ, mármint a verziószám, nem is elérhető).

**Comment by solymosi** [comment]
> Jó és akkor mi tévő legyek végső soron, hogy tudjak váltani a félévek között?

Egyelőre az egyetlen dolog, amit tehetsz, az a Neptun PowerUp! letiltása. A javításhoz szükségünk lesz a @whisperity által említett információkra.

**Comment by bzslrts** [comment]
Én ezt látom. Mire lennétek pontosan kíváncsiak? Vagy az NPU nélküli Neptununkat mutassam?

![Képernyőkép 2022-12-10 133008](https://user-images.githubusercontent.com/119965323/206855222-d8eec85c-7781-4292-86e2-0f918e3c450e.png)

**Comment by bzslrts** [comment]
Így néz ki NPU nélkül. Ez elég? Mit küldjek még?
![Képernyőkép 2022-12-13 134044](https://user-images.githubusercontent.com/119965323/207320738-fa5dc2e9-4d67-4651-8aa1-7e7cf2b5a14b.png)

**Comment by whisperity** [comment]
Debuggoltam kicsit lokálisan ezt, de nem lettem okosabb. Szóval ha jól értem, ez a kód felelős ahhoz, hogy kitalálja, melyik félévben vettek fel:

https://github.com/solymosi/npu/blob/74515be234a5cbdb2768d3a0b3e57e783ca05c0d/src/modules/termSelectorFixes.js#L87-L90

És valóban, nekem:

```js
$("#lblTrainingName").text().match(/:(\d{4}\/\d{2}\/\d)\[.*?\]\)/)
Array [ ":2019/20/1[Nappali])", "2019/20/1" ]
```

Ha kézzel bepötyögöm ami a screenshoton látszik... nem volt egyszerű, de sikerült:

```js
"gazdálkodási és menedzsment - alapképzés (BA/BSc/BProf)(BGAZANM)(Felv. éve:2022/23/1[Nappali]) (Jogv. kezd.:2022.09.01.)".match(/:(\d{4}\/\d{2}\/\d)\[.*?\]\)/)
Array [ ":2022/23/1[Nappali])", "2022/23/1" ]
```

akkor is rendben kiadja amit látni kéne. Tehát nem a reguláris kifejezéssel és a matcheléssel van a baj.

Viszont a te egyetemed konkrét Neptunához való hozzáférés nélkül nem biztos, hogy ennél tovább tudunk érdemben menni. @solymosi Az működhet, ha kérünk tőle egy lementett HTML-t, amiben látjuk a DOM elemeket. Lehet magára a dropdownra nem matchelünk jól?

**Comment by solymosi** [comment]
A Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

Mivel az elmúlt években nem sikerült reprodukálni a bugot, lezárom ezt az issue-t.
