### ISSUE TITLE
Nem lehet belépni amíg az npu aktív

### ISSUE THREAD

**Issue by szabatoro** [solymosi/npu#79]
Ha kikapcsolom a scriptet be tudok lépni, és ha ezután benyomom a scriptet és újratöltöm az oldalt akkor teljesen jól működik az egész. 2-3 napja jelenhetett meg ez a probléma, korábban sose volt ezzel gond. Firefoxot használok.

**Comment by bnctth** [comment]
Ugyanezt tapasztalom egy firefox forkon (LibreWolf 108.0.1, Violentmonkey 2.13.5). Amikor az npu aktív, a `Bejelentkezés` gomb event handlere üres
```js
function onclick(event) {

}
```
míg ha a script le van tiltva, akkor 
```js
function onclick(event) {
  docheck();
  return false;
  __doPostBack('btnSubmit', '')
}
```
A kapott html-ben (`ctrl+U`-val ellenőrizve) szerepel a bejelentkezési kód
```html
<input orgid="hallgato_custom" role="button" type="button" name="btnSubmit" value="Bejelentkezés" onclick="docheck();return&#32;false;__doPostBack(&#39;btnSubmit&#39;,&#39;&#39;)" id="btnSubmit" class="login_button" /><p id=btnSubmit_hiddenlabel class ='hiddenforlabel'></p>
```

---

A vizsgálódás közben kipróbáltam, hogy violentmonkey helyett greasemonkeyt használva működik a bejelentkezés, úgyhogy a jelek szerint a scriptrunnertől függ a hiba megléte. Te mit használsz?

**Comment by szabatoro** [comment]
Pontosítom magam, én is pont ezt a setupot (Librewolf, Violentmonkey) használom. Viszont a hiba már helyrejött. Esélyes, hogy tényleg a Violentmonkey volt a bűnbak, ahogy nézem már updatelt 2.13.7-re.

**Comment by whisperity** [comment]
Bocsánat, én ELTE-s vagyok és nálunk az egész Neptun login rendszert full testre szabták (és a mi saját cuccunkon az NPU! nem is megy), melyik egyetem oldalán jön elő az issue? Vagy tudunk több egyetemről és/vagy úgy általában a Neptun hivatalos beléptető felülete nem működött jól?

LibreWolf 108, ez egy Firefox fork?

**Comment by szabatoro** [comment]
Széchenyi Egyetemről van szó, és igen szerintem az csak a standard neptun login screen. De az előző kolléga sejtése volt valószínűleg helyes, amint kijött az új Violentmonkey verzió, helyreállt a login is.
És igen, a [Librewolf](https://librewolf.net/) egy Firefox fork.
