### ISSUE TITLE
Teljesült féléves speciális indexsorok zöld háttérszíne

### ISSUE THREAD

**Issue by iakos** [solymosi/npu#81]
Sziasztok!

Bele tudnátok tenni kérlek a következő release-be, hogy ne csak a féléves indexsorok, hanem a speciális féléves indexsorok teljesült tételei, tárgyai esetén kapjanak zöld háttérszínt?
    #**h_markbook_gridSpecIndexEntry_bodytable** tr.SubjectCompletedRow td {
      background-color: #D5EFBA !important;
    }
    
Várom a visszajelzéseteket, köszönettel:
Ákos

**Comment by solymosi** [comment]
A Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

Mivel ez az issue a régi Neptun felület feljavításáról szól, most már sajnos nem érdemes foglalkozni vele.
