### ISSUE TITLE
Új Neptun captcha megoldása automatikus bejelentkezéshez

### ISSUE THREAD

**Issue by Mark7888** [solymosi/npu#83]
Egy pár hete egy új funkció került a Neptun bejelentkezéshez (csak néhány egyetemen egyelőre, de gondolom szépen lassan minden egyetem meg fog jelenni), mégpedig egy captcha, ami miatt nem működik az automatikus bejelentkezés.

Fork-oltam a repo-t, és a [TrueCaptcha](https://truecaptcha.org/) API használatával megcsináltam, hogy a neptunkód és jelszó mellett a captcha-t is kitöltse a script automatikusan.

(A truecaptcha nem egy ingyenes szolgáltatás, de nevetségesen olcsó, így nem gondolnám, hogy az embereknek ez a része gondot okozna. 1$-ért cserébe 3000 captcha-t old meg, amit szerintem egy átlag egyetemista a teljes egyetemi képzése alatt sem használna fel)

Lenne rá igény, hogy csináljak egy PullRequest-et és bekerüljön ez is a többi hasznos funkció mellé?

**Comment by Benccccc** [comment]
nekem hasznos lenne!

**Comment by fzs111** [comment]
Nem tudom, hogy ez az a Captcha-e ami nekünk van, de miénkre ez szuperül működik NPU autologinnel is (és teljesen ingyenes): https://github.com/LetsUpdate/CSN

**Comment by solymosi** [comment]
A Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

Mivel ez az issue a Neptun régi felületével kapcsolatos, ezért már nem érdemes foglalkozni vele.
