### ISSUE TITLE
Kiszolgálóhiba történt az alkalmazásban: „/hallgato”.

### ISSUE THREAD

**Issue by epicsepi** [solymosi/npu#86]
Ha be van kapcsolva a script akkor hibaüzenetet dob a Neptun, de eddig hibátlanul ment...
Hibaüzenet:
`Kiszolgálóhiba történt az alkalmazásban: „/hallgato”.`

MacBook, Safari, Tampermonkey, legfrissebb PowerUp.

Köszi a scriptet!

**Comment by gy-mate** [comment]
@epicsepi Melyik egyetem Neptunját használod?

**Comment by solymosi** [comment]
A Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

Emiatt lezárom ezt az issue-t.
