### ISSUE TITLE
Unideb 2024

### ISSUE THREAD

**Issue by pitfla** [solymosi/npu#88]
Sziasztok!

A Neptun mostani frissítése óta nem működik a script.
https://www-h.neptun.unideb.hu/hallgato/main.aspx
Emlékeim szerint nem ezen a címen nyitotta meg eddig a felületet.
A beállításokban a felhasználói hozzárendeléseknél hozzáadtam: https://www-h.neptun.unideb.hu/hallgato/*
Ez nem oldotta meg a problémát.
Nézzétek meg légyszives, mi lehet az oka.
Köszi!

**Comment by solymosi** [comment]
Mit jelent az, hogy _nem működik_?

Ha megnyitom a linket, akkor a login oldalon nálam működik a szkript, ugyanis felkínálja a belépési adatok mentését.

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

**Comment by pitfla** [comment]
Nem volt automatikus belépés és a visszaszámlálás is futott.
De időközben megjavult, ha nem ti csináltatok vele valamit, akkor magától.
A témát le lehet zárni, köszönöm!

Kár, hogy leáll a fejlesztés, de köszönjük az eddigi munkátokat is!
