### ISSUE TITLE
Nem működik a BME hallgatói Neptunon

### ISSUE THREAD

**Issue by gy-mate** [solymosi/npu#89]
~2 hónapja nem működik a szkript a https://neptun.bme.hu/hallgatoi/login.aspx oldalon, be sem töltődik (belépés után se).

**Comment by solymosi** [comment]
Nálam működik a szkript, felkínálja a belépési adatok mentését. Milyen böngészőt használsz?

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

**Comment by gy-mate** [comment]
> Nálam működik a szkript, felkínálja a belépési adatok mentését. Milyen böngészőt használsz?

@solymosi Safari 17.6-ot használok.
A console log sajnos üres, így nem tudom, mi okozhatja a problémát.

**Comment by solymosi** [comment]
A Chromium-alapú böngészőkben újonnan be kell kapcsolni a "developer mode"-ot ahhoz, hogy a Tampermonkey rendesen működjön. Lehet, hogy Safari-n is szükség van hasonlóra? https://www.tampermonkey.net/faq.php?locale=en#Q209

**Comment by gy-mate** [comment]
@solymosi Elvileg nem, de be van kapcsolva nálam a [_Show features for web developers_](https://support.apple.com/en-gb/guide/safari/sfri20948/mac) opció.

**Comment by solymosi** [comment]
Próbáld meg újratelepíteni a Tampermonkey-t. Másoknál már előfordult, hogy ez megoldotta a problémát.
