### ISSUE TITLE
neptun power up SZE nem működik

### ISSUE THREAD

**Issue by h-koppany** [solymosi/npu#91]
Több alkalommal is újra telepítettem a bővítményt, a leírás alapján. Azt írja a böngésző, hogy be van kapcsolva a bővítmény, de semmilyen funkció nem működik a Neptunon.

**Comment by solymosi** [comment]
A belépési oldalon megjelenik a "vissza a legutóbbi oldalra" checkbox? Ha igen, akkor a szkript aktív és működik.

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).
