### ISSUE TITLE
Nem működik a Neptun Power Up az NKE szerveren

### ISSUE THREAD

**Issue by vmakos1** [solymosi/npu#92]
Több alkalommal is újra telepítettem a bővítményt, a leírás alapján, de egyetlen Power Up funkció sem működik a Neptunon :( 

https://neptunweb.uni-nke.hu/hallgato/Login.aspx?timeout=

**Comment by solymosi** [comment]
Amikor én megnyitom a linket, nálam működik a szkript, felkínálja belépéskor az adatok mentését. Milyen böngészőt használsz?

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).
