### ISSUE TITLE
BGE neptunon nem működik 

### ISSUE THREAD

**Issue by b0132** [solymosi/npu#94]

**Comment by solymosi** [comment]
Amikor én megnyitom a hallgatói felületet, nálam működik, felkínálja a belépési adatok mentését. Milyen böngészőt használsz?

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).
