### ISSUE TITLE
PPKE neptun nem működik

### ISSUE THREAD

**Issue by PA1014** [solymosi/npu#95]
Előfordult már többször is, hogy Mac safarin nem működött a powerup miközben többeknek rendesen futott, ekkor még sikerült a powerup factory resettel megoldani a problémát, de viszont mostmár egyáltalán nem fut a script

**Comment by solymosi** [comment]
Amikor megnyitom a PPKE Neptun-t a régi felületen, akkor nálam működik, felkínálja a belépési adatok mentését. Az új felületen nem működik (és várhatóan a jövőben se fog) a Neptun PowerUp!

**Comment by solymosi** [comment]
Fontos: a Neptun PowerUp! fejlesztése várhatóan 2024 végén befejeződik. További részletek a [szkript főoldalán](https://github.com/solymosi/npu).

**Comment by PA1014** [comment]
Szia!
A régi neptun felületen próbáltam futtatni a scriptet és ha rámegyeka bővítményre akkor azt írja ki, hogy fut.
Akkor lehet ez csak személyes probléma, mert körbekérdeztem és van akinek működik is.
Megpróbálom a tampermonkey bővítményt rebootolni, ha ezzel nem oldom meg akkor nem tudom mit tegyek.
Esetleg, ha nem sikerül önerőből megoldanom és csinálnék egy képrenyővideót, akkor rá tudnál nézni?

**Comment by solymosi** [comment]
Próbáld meg bekapcsolni a developer mode-ot a beállításokban: https://www.tampermonkey.net/faq.php#Q209

**Comment by PA1014** [comment]
Sikerült megoldanom azzal, hogy a tampermonkey bővítményt kikapcsoltam, majd újraindítottam.
Észben tartom a te megoldásodat is.
Köszönöm a gyors választ.
